spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pickleball_booking;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vantruongqn7@gmail.com
spring.mail.password=wkhk dilw iszy qhqc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true